# Generated by Django 3.1.4 on 2020-12-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='image',
            field=models.ImageField(default='', upload_to='appeals/'),
        ),
    ]
