# Generated by Django 3.1.4 on 2020-12-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_appeal_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='appeals/'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='tag',
            field=models.ManyToManyField(blank=True, to='donations.Tag'),
        ),
    ]
