# Generated by Django 3.1.4 on 2020-12-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20201218_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='tag',
        ),
    ]
