# Generated by Django 3.1.4 on 2020-12-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20201218_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='appealer',
        ),
    ]
