# Generated by Django 3.1.4 on 2021-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_remove_appeal_appealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='appeal',
            name='image',
            field=models.ImageField(default='appeals/appeal.png', upload_to='appeals/'),
        ),
    ]
