# Generated by Django 3.1.4 on 2021-03-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20210303_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='appealer',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='donations.appealer'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='tag',
            field=models.ManyToManyField(blank=True, to='donations.Tag'),
        ),
    ]
