# Generated by Django 3.1.4 on 2021-03-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20210303_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='appealer',
        ),
    ]
